name: Super-Linter

on:
  pull_request:
    branches: [ master ]

jobs:
  super-lint:
    name: Lint code base
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v1
        - uses: github/super-linter@v3
          with:
            node-version: 16
          - run: cd server
          - run: npm ci        
          - run: npm run build        
          - run: cd ../client
          - run: npm ci        
          - run: npm run build
