name: Super-Linter

on:
  pull_request:
    branches: [ main ]

jobs:
  test_pull_request:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/setup-node@v2
          with:
            node-version: '16'
        - run: npm i --package-lock-only
        - run: npm ci        
        - run: npm run build
