name: Super-Linter

on:
  pull_request:
    branches: [ master ]

jobs:
  test_pull_request:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/setup-node@v2
          with:
            node-version: '16'
        - run: cd server
        - run: npm ci        
        - run: npm run build        
        - run: cd ../client
        - run: npm ci        
        - run: npm run build
